describe('Verify Edit account ', () => {
    beforeEach(() => {
        cy.visit('https://magento.softwaretestingboard.com/customer/account/edit/')
    })
    it('Success edit account', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#firstname').type('abc')
        cy.get('#lastname').type('def')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.contains('You saved the account information').should('be.visible')
    })

    it('Success checkbox Change Email', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.url().should('eq', 'https://magento.softwaretestingboard.com/customer/account/edit/')
        cy.get('#change-email').click()
        cy.contains('Change Email').should('be.visible')
        cy.get('#email').should('be.visible')
        cy.contains('Current Password').should('be.visible')
        cy.get('#current-password').should('be.visible')
    })
    it('Success checkbox Change Password', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.url().should('eq', 'https://magento.softwaretestingboard.com/customer/account/edit/')
        cy.get('#change-password').click()
        cy.contains('Current Password').should('be.visible')
        cy.get('#current-password').should('be.visible')
        cy.contains('New Password').should('be.visible')
        cy.get('#password').should('be.visible')
        cy.contains('Confirm New Password').should('be.visible')
        cy.get('#password-confirmation').should('be.visible')
    })

    it('Success change email', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#change-email').click()
        cy.get('#current-password').should('be.visible')
        cy.get('#current-password').type('@Sanber2025')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.contains('You saved the account information').should('be.visible')
    })
    it.skip('Success change password', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#change-password').click()
        cy.contains('Current Password').should('be.visible')
        cy.get('#current-password').type('@Sanber2025')
        cy.get('#password').type('Sanber2025@')
        cy.get('#password-confirmation').type('Sanber2025@')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.contains('You saved the account information').should('be.visible')
    })

    it('Failed wrong email', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#change-email').click()
        cy.get('#current-password').should('be.visible')
        cy.get('#email').clear().type('abc')
        cy.get('#current-password').type('@Sanber2025')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.contains('Please enter a valid email address.').should('be.visible')
    })

    it('Failed wrong current password', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#change-email').click()
        cy.get('#current-password').should('be.visible')
        cy.get('#current-password').type('abc')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.contains("The password doesn't match this account. Verify the password and try again.").should('be.visible')
    })

    it('Failed empty current password in change password', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#change-password').click()
        cy.contains('Current Password').should('be.visible')
        cy.get('#current-password').should('be.visible')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.contains("This is a required field.").should('be.visible')
    })

    it('Failed wrong current password in change password', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#change-password').click()
        cy.contains('Current Password').should('be.visible')
        cy.get('#current-password').type('abc')
        cy.contains('New Password').should('be.visible')
        cy.get('#password').type('Sanber2025@')
        cy.contains('Confirm New Password').should('be.visible')
        cy.get('#password-confirmation').type('Sanber2025@')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.contains("The password doesn't match this account.").should('be.visible')
    })

    it('Failed empty new password in change password', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#change-password').click()
        cy.contains('Current Password').should('be.visible')
        cy.get('#current-password').type('@Sanber2025')
        cy.contains('New Password').should('be.visible')
        cy.get('#password').type('Sanber2025@')
        cy.contains('Confirm New Password').should('be.visible')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.contains("This is a required field.").should('be.visible')
    })

    it('Failed empty confirmation new password in change password', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#change-password').click()
        cy.contains('Current Password').should('be.visible')
        cy.get('#current-password').type('@Sanber2025')
        cy.contains('New Password').should('be.visible')
        cy.get('#password').type('@Sanber2025')
        cy.contains('Confirm New Password').should('be.visible')
        cy.get('#password-confirmation').should('be.visible')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.contains("This is a required field.").should('be.visible')
    })

    it("Failed confirmation new password did'nt match with new password in change password", () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#change-password').click()
        cy.contains('Current Password').should('be.visible')
        cy.get('#current-password').type('@Sanber2025')
        cy.contains('New Password').should('be.visible')
        cy.get('#password').type('Sanber2025@')
        cy.contains('Confirm New Password').should('be.visible')
        cy.get('#password-confirmation').type('abc')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.contains("Please enter the same value again.").should('be.visible')
    })

    it('Failed input new password under 8 characters in change password', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#change-password').click()
        cy.contains('Current Password').should('be.visible')
        cy.get('#current-password').type('@Sanber2025')
        cy.contains('New Password').should('be.visible')
        cy.get('#password').type('abc')
        cy.contains('Confirm New Password').should('be.visible')
        cy.get('#password-confirmation').type('abc')
        cy.contains("Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored.").should('be.visible')
    })

    it('Failed new password without special characters', () => {
        cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('@Sanber2025')
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#change-password').click()
        cy.contains('Current Password').should('be.visible')
        cy.get('#current-password').type('@Sanber2025')
        cy.contains('New Password').should('be.visible')
        cy.get('#password').type('1234abcd')
        cy.contains('Confirm New Password').should('be.visible')
        cy.get('#password-confirmation').type('1234abcd')
        cy.contains("Minimum of different classes of characters in password is 3. Classes of characters: Lower Case, Upper Case, Digits, Special Characters.").should('be.visible')
    })

})