describe('Proceed to Checkout', () => {
  beforeEach(() => {
    cy.visit('https://magento.softwaretestingboard.com/')
  })
  it('Succsesfuly Proceed', () => {
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.url().should('include','login')
    cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
    cy.get('#pass').type('@Sanber2025')
    cy.get('#send2').click()
    cy.get('.base').should('have.text','Home Page')
    cy.get(':nth-child(1) > .product-item-info > .product-item-photo > .product-image-container > .product-image-wrapper > .product-image-photo').click()
    cy.get('.base').should('have.text','Radiant Tee')
    cy.wait(3000)
    cy.get('#option-label-size-143-item-166').click()
    cy.get('#option-label-color-93-item-50').click()
    cy.get('#product-addtocart-button').click()
    cy.wait(3000)
    cy.get('.message-success').should('contain.text','added')
    cy.get('.showcart').click()
    cy.get('.subtotal > .label > span').should('contain.text','Cart')
    cy.get('#top-cart-btn-checkout').should("be.visible").click()
    cy.wait(10000)
    cy.url().should('include','shipping')
    cy.get('[name="shippingAddress.company"]').type('Kelompok9')
    cy.get('[name="street[0]"]').type('SanberCode')
    cy.get('[name="shippingAddress.city"]').type('Sanber64')
    cy.get('[name="region_id"]').select(1)
    cy.get('[name="shippingAddress.postcode"]').type('12310')
    cy.get('[name="country_id"]').select('ID')
    cy.get('[name="shippingAddress.telephone"]').type('6285892999999')
    cy.wait(5000)
    cy.get('[name="shippingAddress.region"]').type('JAKARTA')
    cy.get('.button').click()
    cy.wait(10000)
    cy.get('.payment-method-content > :nth-child(4) > div.primary > .action').click()
    cy.get('.base').should('contain.text','Thank you')
    cy.url().should('include','success')
  })

  it('Successfully Proceeded with an Existing Address', () => {
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.url().should('include','login')
    cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
    cy.get('#pass').type('@Sanber2025')
    cy.get('#send2').click()
    cy.get('.base').should('have.text','Home Page')
    cy.get(':nth-child(1) > .product-item-info > .product-item-photo > .product-image-container > .product-image-wrapper > .product-image-photo').click()
    cy.get('.base').should('have.text','Radiant Tee')
    cy.wait(3000)
    cy.get('#option-label-size-143-item-166').click()
    cy.get('#option-label-color-93-item-50').click()
    cy.get('#product-addtocart-button').click()
    cy.wait(3000)
    cy.get('.message-success').should('contain.text','added')
    cy.get('.showcart').click()
    cy.get('.subtotal > .label > span').should('contain.text','Cart')
    cy.get('#top-cart-btn-checkout').should("be.visible").click()
    cy.wait(10000)
    cy.get('.new-address-popup > .action').should('contain.text','New')
    cy.get('.button').click()
    cy.wait(10000)
    cy.get('.payment-method-content > :nth-child(4) > div.primary > .action').click()
    cy.get('.base').should('contain.text','Thank you')
    cy.url().should('include','success')
  })

  it('Failed Create a New Address', () => {
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.url().should('include','login')
    cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
    cy.get('#pass').type('@Sanber2025')
    cy.get('#send2').click()
    cy.get('.base').should('have.text','Home Page')
    cy.get(':nth-child(1) > .product-item-info > .product-item-photo > .product-image-container > .product-image-wrapper > .product-image-photo').click()
    cy.get('.base').should('have.text','Radiant Tee')
    cy.wait(3000)
    cy.get('#option-label-size-143-item-166').should("be.visible").click()
    cy.get('#option-label-color-93-item-50').click()
    cy.get('#product-addtocart-button').click()
    cy.wait(3000)
    cy.get('.message-success').should('contain.text','added')
    cy.get('.showcart').click()
    cy.get('.subtotal > .label > span').should('contain.text','Cart')
    cy.get('#top-cart-btn-checkout').should("be.visible").click()
    cy.wait(10000)
    cy.get('.new-address-popup > .action').should('contain.text','New')
    cy.get('.new-address-popup > .action').click()
    cy.get('.modal-footer > .primary').click()
    cy.get('.street').should('contain.text','required field.')
    cy.get('[name="shippingAddress.city"]').should('contain.text','required field.')
    cy.get('[name="shippingAddress.region_id"]').should('contain.text','required field.')
    cy.get('[name="shippingAddress.postcode"]').should('contain.text','required field.')
    cy.get('[name="shippingAddress.telephone"]').should('contain.text','required field.')
  })

  it('Failed to create a new address due to missing required information', () => {
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.url().should('include','login')
    cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
    cy.get('#pass').type('@Sanber2025')
    cy.get('#send2').click()
    cy.get('.base').should('have.text','Home Page')
    cy.get(':nth-child(1) > .product-item-info > .product-item-photo > .product-image-container > .product-image-wrapper > .product-image-photo').click()
    cy.get('.base').should('have.text','Radiant Tee')
    cy.wait(3000)
    cy.get('#option-label-size-143-item-166').should("be.visible").click()
    cy.get('#option-label-color-93-item-50').click()
    cy.get('#product-addtocart-button').click()
    cy.wait(3000)
    cy.get('.message-success').should('contain.text','added')
    cy.get('.showcart').click()
    cy.get('.subtotal > .label > span').should('contain.text','Cart')
    cy.get('#top-cart-btn-checkout').should("be.visible").click()
    cy.wait(10000)
    cy.get('.new-address-popup > .action').should('contain.text','New')
    cy.get('.new-address-popup > .action').click()
    cy.get('[name="shippingAddress.company"]').type('Kelompok9')
    cy.get('.modal-footer > .primary').click()
    cy.get('.street').should('contain.text','required field.')
    cy.get('[name="shippingAddress.city"]').should('contain.text','required field.')
    cy.get('[name="shippingAddress.region_id"]').should('contain.text','required field.')
    cy.get('[name="shippingAddress.postcode"]').should('contain.text','required field.')
    cy.get('[name="shippingAddress.telephone"]').should('contain.text','required field.')
  })

  it('Failed to create a new address because the Street Address field is empty.', () => {
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.url().should('include','login')
    cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
    cy.get('#pass').type('@Sanber2025')
    cy.get('#send2').click()
    cy.get('.base').should('have.text','Home Page')
    cy.get(':nth-child(1) > .product-item-info > .product-item-photo > .product-image-container > .product-image-wrapper > .product-image-photo').click()
    cy.get('.base').should('have.text','Radiant Tee')
    cy.wait(3000)
    cy.get('#option-label-size-143-item-166').should("be.visible").click()
    cy.get('#option-label-color-93-item-50').click()
    cy.get('#product-addtocart-button').click()
    cy.wait(3000)
    cy.get('.message-success').should('contain.text','added')
    cy.get('.showcart').click()
    cy.get('.subtotal > .label > span').should('contain.text','Cart')
    cy.get('#top-cart-btn-checkout').should("be.visible").click()
    cy.wait(10000)
    cy.get('.new-address-popup > .action').should('contain.text','New')
    cy.get('.new-address-popup > .action').click()
    cy.get('[name="shippingAddress.company"]').type('Kelompok9')
    cy.get('[name="shippingAddress.city"]').type('New')
    cy.get('[name="region_id"]').select(1)
    cy.get('[name="shippingAddress.postcode"]').type('12310')
    cy.get('[name="country_id"]').select('ID')
    cy.get('[name="shippingAddress.telephone"]').type('6285892999999')
    cy.get('#shipping-save-in-address-book').click()
    cy.get('.modal-footer > .primary').click()
    cy.get('.street').should('contain.text','required field.')
  })

  it('Failed to create a new address because the City field is empty.', () => {
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.url().should('include','login')
    cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
    cy.get('#pass').type('@Sanber2025')
    cy.get('#send2').click()
    cy.get('.base').should('have.text','Home Page')
    cy.get(':nth-child(1) > .product-item-info > .product-item-photo > .product-image-container > .product-image-wrapper > .product-image-photo').click()
    cy.get('.base').should('have.text','Radiant Tee')
    cy.wait(3000)
    cy.get('#option-label-size-143-item-166').should("be.visible").click()
    cy.get('#option-label-color-93-item-50').click()
    cy.get('#product-addtocart-button').click()
    cy.wait(3000)
    cy.get('.message-success').should('contain.text','added')
    cy.get('.showcart').click()
    cy.get('.subtotal > .label > span').should('contain.text','Cart')
    cy.get('#top-cart-btn-checkout').should("be.visible").click()
    cy.wait(10000)
    cy.get('.new-address-popup > .action').should('contain.text','New')
    cy.get('.new-address-popup > .action').click()
    cy.get('[name="shippingAddress.company"]').type('Kelompok9')
    cy.get('[name="street[0]"]').type('SanberCode')
    cy.get('[name="region_id"]').select(1)
    cy.get('[name="shippingAddress.postcode"]').type('12310')
    cy.get('[name="country_id"]').select('ID')
    cy.get('[name="shippingAddress.telephone"]').type('6285892999999')
    cy.get('#shipping-save-in-address-book').click()
    cy.get('.modal-footer > .primary').click()
    cy.get('[name="shippingAddress.city"]').should('contain.text','required field.')
  })

  it('Failed to create a new address because the Postal Code field is empty.', () => {
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.url().should('include','login')
    cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
    cy.get('#pass').type('@Sanber2025')
    cy.get('#send2').click()
    cy.get('.base').should('have.text','Home Page')
    cy.get(':nth-child(1) > .product-item-info > .product-item-photo > .product-image-container > .product-image-wrapper > .product-image-photo').click()
    cy.get('.base').should('have.text','Radiant Tee')
    cy.wait(3000)
    cy.get('#option-label-size-143-item-166').should("be.visible").click()
    cy.get('#option-label-color-93-item-50').click()
    cy.get('#product-addtocart-button').click()
    cy.wait(3000)
    cy.get('.message-success').should('contain.text','added')
    cy.get('.showcart').click()
    cy.get('.subtotal > .label > span').should('contain.text','Cart')
    cy.get('#top-cart-btn-checkout').should("be.visible").click()
    cy.wait(10000)
    cy.get('.new-address-popup > .action').should('contain.text','New')
    cy.get('.new-address-popup > .action').click()
    cy.get('[name="shippingAddress.company"]').type('Kelompok9')
    cy.get('[name="street[0]"]').type('SanberCode')
    cy.get('[name="shippingAddress.city"]').type('Sanber')
    cy.get('[name="region_id"]').select(1)
    cy.get('[name="country_id"]').select('ID')
    cy.get('[name="shippingAddress.telephone"]').type('6285892999999')
    cy.get('#shipping-save-in-address-book').click()
    cy.get('.modal-footer > .primary').click()
    cy.get('[name="shippingAddress.postcode"]').should('contain.text','required field.')
  })

  it('Failed to create a new address because the Phone Number field is empty.', () => {
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.url().should('include','login')
    cy.get('#email').type('kelompok9_sanber_sqa@gmail.com')
    cy.get('#pass').type('@Sanber2025')
    cy.get('#send2').click()
    cy.get('.base').should('have.text','Home Page')
    cy.get(':nth-child(1) > .product-item-info > .product-item-photo > .product-image-container > .product-image-wrapper > .product-image-photo').click()
    cy.get('.base').should('have.text','Radiant Tee')
    cy.wait(3000)
    cy.get('#option-label-size-143-item-166').should("be.visible").click()
    cy.get('#option-label-color-93-item-50').click()
    cy.get('#product-addtocart-button').click()
    cy.wait(3000)
    cy.get('.message-success').should('contain.text','added')
    cy.get('.showcart').click()
    cy.get('.subtotal > .label > span').should('contain.text','Cart')
    cy.get('#top-cart-btn-checkout').should("be.visible").click()
    cy.wait(10000)
    cy.get('.new-address-popup > .action').should('contain.text','New')
    cy.get('.new-address-popup > .action').click()
    cy.get('[name="shippingAddress.company"]').type('Kelompok9')
    cy.get('[name="street[0]"]').type('SanberCode')
    cy.get('[name="shippingAddress.city"]').type('Sanber')
    cy.get('[name="region_id"]').select(1)
    cy.get('[name="shippingAddress.postcode"]').type('12310')
    cy.get('[name="country_id"]').select('ID')
    cy.get('#shipping-save-in-address-book').click()
    cy.get('.modal-footer > .primary').click()
    cy.get('[name="shippingAddress.telephone"]').should('contain.text','required field.')
  })
})